---
title: "Behavior Data Plots version 7"
author: Jeffrey Brown
Created: 02-12-2024
Last Updated: 03-05-2024
format: html
editor: visual
---

#setup

```{r}
library(openxlsx) 
library(dplyr) 
library(tidyverse) 
library(magrittr) 
library(glue) 
library(ggformula) 
library(vctrs) 
library(snakecase) 
library(gridExtra)
library(devtools)
install_github(repo = 'https://github.com/JeffreyDeanBrown/BehaviorGraphs',
               subdir = "BehaviorGraphs")
library(BehaviorGraphs)
options(dplyr.summarise.inform = FALSE)

spreadsheet_name <- c('Behavior Data 01-08-24.xlsx')

setwd("/mnt/Windows_E/Syncthing/R_projects/Mouse Behavior/mouse_behavior_graphs")


data <- get_the_data()  #Do not change the name of this 'data' tibble unless you also change Glue Functions.R
print("Done with Setup")
```

#Make all of the graphs

```{r}
# You can edit group_subtitle and indiv_subtitle  variables to change the
# subtitles on your grouped graphs or individual mouse graphs, respectively
# 
#
# The syntax for the subtitles is as follows:
#
# group graphs:
# {.data$genotype} is converted to the group's genotype, 
# {.data$n} is converted to the n-value for that group
#
# individual graphs:
# {.data$number} is the mouse's tag number,
# {.data$sex} is the mouse's sex,
# {.data\$cage} is the mouse's cage
# 
# \n makes a new line when the subtitle is printed on the graph


process_all_the_data(group_subtitle = "{.data$genotype} (n = {.data$n})",
                     indiv_subtitle = "Mouse \n {.data$number}, {.data$sex}, {.data$genotype}\n From cage: {.data$cage}")

#previous system time: 
# 22.062 seconds without individuals
# 146.272 seconds with all individuals

#system time with minor performance update:
# 22.224 seconds without individuals
# 120.563 seconds with all individuals
```

#Make a custom graph

```{r}
# To generate a custom graph, you must run generate_custom_graphs()
# To see what genotypes you can choose, run show_custom_options()

show_custom_options()

generate_custom_graphs(genotypes_to_plot = c("pFlp Homo (Male)", "OSKO Homo wSOD1M (Female)"),
                       graph_to_preview = "weight_plot")
# NOTE: generate_custom_graphs can also take custom subtitles by providing
#       group_subtitle using the same syntax from process_all_the_data
#
#           example:   group_subtitle = "{.data$genotype} (n = {.data$n})"
# 
#
#
#
# Once you are happy with your custom graph, you can print all of the graphs
# (i.e. grip strength, weight, rotarod, etc.) by running print_custom_graphs()
# which will print a pdf "Custom Graphs.pdf" with your graphs

print_custom_graphs()

```
