# pdf Functions.R
# version 1.2
# last update 03-02-2024
#
# FUNCTIONS: print_with_indiv, print_without_indiv, print_custom_graphs
#
# DEPENDS:  process_all_the_data (creates the names for the nested lists of graphs)
#           plot_the_group and plot_the_indiv (name the plot columns)
#           label_the_data (labels the "group" column)
#           create_labels_cols (labels the "sod1_group" column)
#   (DEPENDS needs to be updated)
#          
# DESCRIPTION:
# These functions take the graphs made by gg_plot and output them into pdfs
# 
# The name of the pdf files can be changed by changing the text pdf("text")
# 
# The other code depends on labels generated by other functions and should not be 
# changed unless you have are also making significant changes to code in other 
# source files

#----------------------------------------------------------------------------------
print_with_indiv <- function(filename_of_the_day) {
  print("Printing graphs...")
  dir.create("PDFs")

  
#Export PDFs by genotype (or by sod1 group) followed by all individual mice graphs

#pFlp


list <- c(genotype_group$grip_plot[which(str_detect(genotype_group$group,"pFlp"))]      ,
genotype_group$weight_plot[which(str_detect(genotype_group$group,"pFlp"))]    ,
genotype_group$s_rotarod_plot[which(str_detect(genotype_group$group,"pFlp"))] ,
genotype_group$t_rotarod_plot[which(str_detect(genotype_group$group,"pFlp"))] ,
genotype_group$condition_plot[which(str_detect(genotype_group$group,"pFlp"))] ,
indiv_$grip_plot[which(str_detect(indiv_$group,"pFlp"))]                      ,
indiv_$weight_plot[which(str_detect(indiv_$group,"pFlp"))]                    ,
indiv_$s_rotarod_plot[which(str_detect(indiv_$group,"pFlp"))]                 ,
indiv_$s_rotarod_plot[which(str_detect(indiv_$group,"pFlp"))]                 ,
indiv_$condition_plot[which(str_detect(indiv_$group,"pFlp"))]) 

ggsave(filename = "PDFs/pFlp.pdf", plot = marrangeGrob(grobs = list, nrow = 1, ncol = 1),
       width = 7, height = 7)          


#genotype to be graphed today

list <- c(genotype_group$grip_plot[which(str_detect(genotype_group$group,genotype_of_the_day))]      ,
genotype_group$weight_plot[which(str_detect(genotype_group$group,genotype_of_the_day))]    ,
genotype_group$s_rotarod_plot[which(str_detect(genotype_group$group,genotype_of_the_day))] ,
genotype_group$t_rotarod_plot[which(str_detect(genotype_group$group,genotype_of_the_day))] ,
genotype_group$condition_plot[which(str_detect(genotype_group$group,genotype_of_the_day))] ,
indiv_$grip_plot[which(str_detect(indiv_$group,genotype_of_the_day))]                      ,
indiv_$weight_plot[which(str_detect(indiv_$group,genotype_of_the_day))]                    ,
indiv_$s_rotarod_plot[which(str_detect(indiv_$group,genotype_of_the_day))]                 ,
indiv_$s_rotarod_plot[which(str_detect(indiv_$group,genotype_of_the_day))]                 ,
indiv_$condition_plot[which(str_detect(indiv_$group,genotype_of_the_day))]) 

ggsave(filename = filename_of_the_day, plot = marrangeGrob(grobs = list, nrow = 1, ncol = 1),
       width = 7, height = 7)


#SOD1m

list <- c(sod1_group %>% subset(sod1_group == 'SOD1mut') %>% pluck('grip_plot')      ,
sod1_group %>% subset(sod1_group == 'SOD1mut') %>% pluck('weight_plot')    ,
sod1_group %>% subset(sod1_group == 'SOD1mut') %>% pluck('s_rotarod_plot') ,
sod1_group %>% subset(sod1_group == 'SOD1mut') %>% pluck('t_rotarod_plot') ,
sod1_group %>% subset(sod1_group == 'SOD1mut') %>% pluck('condition_plot') ,
indiv_     %>% subset(sod1_group == 'SOD1mut') %>% pluck('grip_plot')      ,
indiv_     %>% subset(sod1_group == 'SOD1mut') %>% pluck('weight_plot')    ,
indiv_     %>% subset(sod1_group == 'SOD1mut') %>% pluck('s_rotarod_plot') ,
indiv_     %>% subset(sod1_group == 'SOD1mut') %>% pluck('s_rotarod_plot') ,
indiv_     %>% subset(sod1_group == 'SOD1mut') %>% pluck('condition_plot'))

ggsave(filename = "PDFs/mutant SOD1.pdf", plot = marrangeGrob(grobs = list, nrow = 1, ncol = 1),
       width = 7, height = 7)
#SOD1wt

list <- c(sod1_group %>% subset(sod1_group == 'SOD1wt') %>% pluck('grip_plot')      ,
sod1_group %>% subset(sod1_group == 'SOD1wt') %>% pluck('weight_plot')    ,
sod1_group %>% subset(sod1_group == 'SOD1wt') %>% pluck('s_rotarod_plot') ,
sod1_group %>% subset(sod1_group == 'SOD1wt') %>% pluck('t_rotarod_plot') ,
sod1_group %>% subset(sod1_group == 'SOD1wt') %>% pluck('condition_plot') ,
indiv_     %>% subset(sod1_group == 'SOD1wt') %>% pluck('grip_plot')      ,
indiv_     %>% subset(sod1_group == 'SOD1wt') %>% pluck('weight_plot')    ,
indiv_     %>% subset(sod1_group == 'SOD1wt') %>% pluck('s_rotarod_plot') ,
indiv_     %>% subset(sod1_group == 'SOD1wt') %>% pluck('s_rotarod_plot') ,
indiv_     %>% subset(sod1_group == 'SOD1wt') %>% pluck('condition_plot'))

ggsave(filename = "PDFs/wildtype SOD1.pdf", plot = marrangeGrob(grobs = list, nrow = 1, ncol = 1),
       width = 7, height = 7)
}




#-----------------------------------------------------------------------------------------
print_without_indiv <- function(filename_of_the_day){
  #Export PDFs by genotype (or by sod1 group) followed by all individual mice graphs
  print("Printing graphs...")
  dir.create("PDFs")
  
  #pFlp
  
  list <- c(genotype_group$grip_plot[which(str_detect(genotype_group$group,"pFlp"))]      ,
  genotype_group$weight_plot[which(str_detect(genotype_group$group,"pFlp"))]    ,
  genotype_group$s_rotarod_plot[which(str_detect(genotype_group$group,"pFlp"))] ,
  genotype_group$t_rotarod_plot[which(str_detect(genotype_group$group,"pFlp"))] ,
  genotype_group$condition_plot[which(str_detect(genotype_group$group,"pFlp"))])
  
  ggsave(filename = "PDFs/pFlp.pdf", plot = marrangeGrob(grobs = list, nrow = 1, ncol = 1),
         width = 7, height = 7)
  
  #genotype to be graphed today
  
  list <- c(genotype_group$grip_plot[which(str_detect(genotype_group$group,genotype_of_the_day))]      ,
  genotype_group$weight_plot[which(str_detect(genotype_group$group,genotype_of_the_day))]    ,
  genotype_group$s_rotarod_plot[which(str_detect(genotype_group$group,genotype_of_the_day))] ,
  genotype_group$t_rotarod_plot[which(str_detect(genotype_group$group,genotype_of_the_day))] ,
  genotype_group$condition_plot[which(str_detect(genotype_group$group,genotype_of_the_day))]) 
  
  ggsave(filename = filename_of_the_day, plot = marrangeGrob(grobs = list, nrow = 1, ncol = 1),
         width = 7, height = 7)
  
  
  #SOD1m
  
  list <- c(sod1_group %>% subset(sod1_group == 'SOD1mut') %>% pluck('grip_plot')      ,
  sod1_group %>% subset(sod1_group == 'SOD1mut') %>% pluck('weight_plot')    ,
  sod1_group %>% subset(sod1_group == 'SOD1mut') %>% pluck('s_rotarod_plot') ,
  sod1_group %>% subset(sod1_group == 'SOD1mut') %>% pluck('t_rotarod_plot') ,
  sod1_group %>% subset(sod1_group == 'SOD1mut') %>% pluck('condition_plot'))
  
  ggsave(filename = "PDFs/mutant SOD1.pdf", plot = marrangeGrob(grobs = list, nrow = 1, ncol = 1),
         width = 7, height = 7)
  
  #SOD1wt
  
  list <- c(sod1_group %>% subset(sod1_group == 'SOD1wt') %>% pluck('grip_plot')      ,
  sod1_group %>% subset(sod1_group == 'SOD1wt') %>% pluck('weight_plot')    ,
  sod1_group %>% subset(sod1_group == 'SOD1wt') %>% pluck('s_rotarod_plot') ,
  sod1_group %>% subset(sod1_group == 'SOD1wt') %>% pluck('t_rotarod_plot') ,
  sod1_group %>% subset(sod1_group == 'SOD1wt') %>% pluck('condition_plot'))
  
  ggsave(filename = "PDFs/wildtype SOD1.pdf", plot = marrangeGrob(grobs = list, nrow = 1, ncol = 1),
         width = 7, height = 7)
  
  #All mice
  
  list <- c(all_group %>% pluck('grip_plot')      ,
  all_group %>% pluck('weight_plot')    ,
  all_group %>% pluck('s_rotarod_plot') ,
  all_group %>% pluck('t_rotarod_plot') ,
  all_group %>% pluck('condition_plot'))
  
  ggsave(filename = "PDFs/all mice.pdf", plot = marrangeGrob(grobs = list, nrow = 1, ncol = 1),
         width = 7, height = 7)

}

#------------------------------------------------------------------------------------------------------

print_custom_graphs <- function(){
  
  
  list <- c(custom_graphs %>% pluck('grip_plot')      ,
  custom_graphs %>% pluck('weight_plot')    ,
  custom_graphs %>% pluck('s_rotarod_plot') ,
  custom_graphs %>% pluck('t_rotarod_plot') ,
  custom_graphs %>% pluck('condition_plot'))
  
  ggsave(filename = "PDFs/Custom Graphs.pdf", plot = marrangeGrob(grobs = list, nrow = 1, ncol = 1),
         width = 7, height = 7)
  
  
}

