# pdf Functions.R
# version 1.2
# last update 03-02-2024
#
# FUNCTIONS: print_with_indiv, print_without_indiv, print_custom_graphs
#
# DEPENDS:  plot_the_data (creates the names for the nested lists of graphs)
#           plot_the_group and plot_individuals (name the plot columns)
#           label_the_data (labels the "group" column)
#           create_labels_cols (labels the "sod1_factor" column)
#   (DEPENDS needs to be updated)
#          
# DESCRIPTION:
# These functions take the graphs made by gg_plot and output them into pdfs
# 
# The name of the pdf files can be changed by changing the text suppressWarnings(pdf("text")
# 
# The other code depends on labels generated by other functions and should not be 
# changed unless you have are also making significant changes to code in other 
# source files

#----------------------------------------------------------------------------------
print_with_indiv <- function() {
  print("Printing graphs...")
  dir.create("PDFs")

measurements <- c("grip_plot", "weight_plot", "s_rotarod_plot", "t_rotarod_plot", "condition_plot")

#genotype groups 

group_to_print = c("pFlp", genotype_of_the_day)
pdf_names     = c("pFlp.pdf", filename_of_the_day)

map2(group_to_print, pdf_names, ~
       
  lister <- function(.data, look_up_vector){
    subset(.data, subset = str_detect(look_up_vector, .x), select = measurements) %>%
    unlist(recursive= FALSE, use.names = FALSE)
  }

  group_list <- genotype_group %>% lister(look_up_vector = genotype_group$group)
  indiv_list <- indiv_         %>% lister(look_up_vector = indiv_$group)

  suppressWarnings(pdf(glue("PDFs/{.y}")))
  append(group_list, indiv_list) %>% lapply(print)
  dev.off()
)

#SOD1 groups
# group_to_print = c("SOD1mut", "SOD1wt")
# pdf_names     = c("mutant SOD1.pdf", "wildtype SOD1.pdf")
# look_up_column = sod1_factor
# .data = sod1_group

# within .data and indiv, everything in column look_up_column with string group_to_print is printed to
# a pdf in PDFs/ named pdf_names
printer <- function(.data, groups_to_print, pdf_names, look_up_column){

  map2(group_to_print, pdf_names, ~
       lister <- function(.database, look_up_column){
         subset(.database, subset = str_detect(look_up_column, .x), select = measurements) %>%
           unlist(recursive= FALSE, use.names = FALSE)
       }
       
       group_list <- lister(.data)
       indiv_list <- lister(indiv_)
       
       suppressWarnings(pdf(glue("PDFs/{.y}")))
       append(group_list, indiv_list) %>% lapply(print)
       dev.off()
  )
}




#-----------------------------------------------------------------------------------------
print_without_indiv <- function(){
  #Export PDFs by genotype (or by sod1 group) followed by all individual mice graphs
  print("Printing graphs...")
  dir.create("PDFs")
  
  #pFlp
  
  plot_list <- c(genotype_group$grip_plot[which(str_detect(genotype_group$group,"pFlp"))]      ,
  genotype_group$weight_plot[which(str_detect(genotype_group$group,"pFlp"))]    ,
  genotype_group$s_rotarod_plot[which(str_detect(genotype_group$group,"pFlp"))] ,
  genotype_group$t_rotarod_plot[which(str_detect(genotype_group$group,"pFlp"))] ,
  genotype_group$condition_plot[which(str_detect(genotype_group$group,"pFlp"))])
  
  suppressWarnings(pdf("PDFs/pFlp.pdf"))
lapply(plot_list, print)
dev.off()

  
  #genotype to be graphed today
  
  plot_list <- c(genotype_group$grip_plot[which(str_detect(genotype_group$group,genotype_of_the_day))]      ,
  genotype_group$weight_plot[which(str_detect(genotype_group$group,genotype_of_the_day))]    ,
  genotype_group$s_rotarod_plot[which(str_detect(genotype_group$group,genotype_of_the_day))] ,
  genotype_group$t_rotarod_plot[which(str_detect(genotype_group$group,genotype_of_the_day))] ,
  genotype_group$condition_plot[which(str_detect(genotype_group$group,genotype_of_the_day))]) 
  
  suppressWarnings(pdf(filename_of_the_day))
lapply(plot_list, print)
dev.off()

  
  
  #SOD1m
  
  plot_list <- c(sod1_group %>% subset(sod1_factor == 'SOD1mut') %>% pluck('grip_plot')      ,
  sod1_group %>% subset(sod1_factor == 'SOD1mut') %>% pluck('weight_plot')    ,
  sod1_group %>% subset(sod1_factor == 'SOD1mut') %>% pluck('s_rotarod_plot') ,
  sod1_group %>% subset(sod1_factor == 'SOD1mut') %>% pluck('t_rotarod_plot') ,
  sod1_group %>% subset(sod1_factor == 'SOD1mut') %>% pluck('condition_plot'))
  
  suppressWarnings(pdf("PDFs/mutant SOD1.pdf"))
lapply(plot_list, print)
dev.off()

  
  #SOD1wt
  
  plot_list <- c(sod1_group %>% subset(sod1_factor == 'SOD1wt') %>% pluck('grip_plot')      ,
  sod1_group %>% subset(sod1_factor == 'SOD1wt') %>% pluck('weight_plot')    ,
  sod1_group %>% subset(sod1_factor == 'SOD1wt') %>% pluck('s_rotarod_plot') ,
  sod1_group %>% subset(sod1_factor == 'SOD1wt') %>% pluck('t_rotarod_plot') ,
  sod1_group %>% subset(sod1_factor == 'SOD1wt') %>% pluck('condition_plot'))
  
  suppressWarnings(pdf("PDFs/wildtype SOD1.pdf"))
lapply(plot_list, print)
dev.off()

  
  #All mice
  
  plot_list <- c(all_group %>% pluck('grip_plot')      ,
  all_group %>% pluck('weight_plot')    ,
  all_group %>% pluck('s_rotarod_plot') ,
  all_group %>% pluck('t_rotarod_plot') ,
  all_group %>% pluck('condition_plot'))
  
  suppressWarnings(pdf("PDFs/all mice.pdf"))
lapply(plot_list, print)
dev.off()


}

#------------------------------------------------------------------------------------------------------

print_custom_graphs <- function(){
  
  
  plot_list <- c(custom_graphs %>% pluck('grip_plot')      ,
  custom_graphs %>% pluck('weight_plot')    ,
  custom_graphs %>% pluck('s_rotarod_plot') ,
  custom_graphs %>% pluck('t_rotarod_plot') ,
  custom_graphs %>% pluck('condition_plot'))
  
  suppressWarnings(pdf("PDFs/Custom Graphs.pdf"))
lapply(plot_list, print)
dev.off()

  
  
}

