# pdf Functions.R
# version 1.2
# last update 03-02-2024
#
# FUNCTIONS: print_the_plots, print_without_indiv, print_custom_graphs
#
# DEPENDS:  plot_the_data (creates the names for the nested lists of graphs)
#           plot_the_group and plot_individuals (name the plot columns)
#           label_the_data (labels the "group" column)
#           create_labels_cols (labels the "sod1_factor" column)
#   (DEPENDS needs to be updated)
#          
# DESCRIPTION:
# These functions take the graphs made by gg_plot and output them into pdfs
# 
# The name of the pdf files can be changed by changing the text suppressWarnings(pdf("text")
# 
# The other code depends on labels generated by other functions and should not be 
# changed unless you have are also making significant changes to code in other 
# source files




print_the_plots <- function() {

  print("Do you want to print individual mice plots? [y/n] (it will be slower)")
  repeat {
    resp <<- readline()               #takes an input from the console
    if (resp == "y"){break}
    else if (resp == "n"){break}
    else{print("ERROR: please enter a 'y' or a 'n'")}
  }
  measurements <<- c("grip_plot", "weight_plot", "s_rotarod_plot", "t_rotarod_plot", "condition_plot")

  print("Printing graphs...")
  suppressWarnings(dir.create("PDFs"))

  look_up_vector <<- genotype_group$group
  printer(.data = genotype_group,
          group_to_print = c("pFlp", genotype_of_the_day),
          pdf_names     = c("pFlp.pdf", filename_of_the_day))

  look_up_vector <<- sod1_group$sod1_factor
  printer(.data = sod1_group,
          group_to_print = c("SOD1mut", "SOD1wt"),
          pdf_names     = c("mutant SOD1.pdf", "wildtype SOD1.pdf"))


  look_up_vector <<- all_group$all
  resp <<- "n" #don't print any indivs in all mice.pdf
  printer(.data = all_group,
          group_to_print = "all",
          pdf_names      = "all mice.pdf")


rm(resp, inherits = TRUE)
rm(look_up_vector, inherits = TRUE)
rm(measurements, inherits = TRUE)
}





# within .data, everything in column look_up_vector with string group_to_print is printed to
# a pdf in PDFs/ named pdf_names
printer <- function(.data, group_to_print, pdf_names){


  # just do a for loop against c(1:length(group_to_print)), then index into group_to_print and pdf_names
  # to avoid messing with map
  
  map2(group_to_print, pdf_names, function(x,y){
       lister <- function(.database){
         subset(.database, subset = str_detect(look_up_vector, x), select = measurements) %>%
           unlist(recursive= FALSE, use.names = FALSE)
       }
       
       plot_list <- lister(.data)

       if(resp == "y"){
       indiv_list <- lister(indiv_)
       plot_list <- append(plot_list, indiv_list)
       }

       suppressWarnings(pdf(glue("PDFs/{y}")))
       lapply(plot_list, print)
       dev.off()
    }
  )
}

